version: '3.7'
services:

  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - whoopzee
    ports: 
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s

#############################################################################################
###                                       Network                                         ###
#############################################################################################

networks:
  whoopzee:
    driver: "bridge"
